development:
  database: mini_project
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
test:
  database: mini_project_test
  username: root
  password: qwer4321
  adapter: mysql2
  encoding: utf8mb4
  host: db
